# File @generated by hack/generate-authors.sh. DO NOT EDIT.
# This file lists all contributors to the repository.
# See hack/generate-authors.sh to make modifications.

Fatima Ait Brahim <fatimaaitbrahim18@gmail.com>
Anis Emad <anisemad123@gmail.com>
